"use client";
import { FormEvent, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { saveCompanyJobPosting } from "./job-posting-api";
import type { JobPosting, JobPostingInput } from "./job-posting-types";
import styles from "./job-postings.module.css";

export function JobPostingForm({ posting, companyProfile }: { posting: JobPosting | null; companyProfile?: { description: string | null; website_url: string | null } }) {
  const router = useRouter(); const [value, setValue] = useState<JobPostingInput>({ title: posting?.title ?? "", description: posting?.description ?? "", work_conditions: posting?.work_conditions ?? "", company_description: posting?.company_description ?? companyProfile?.description ?? "", company_website_url: posting?.company_website_url ?? companyProfile?.website_url ?? "", status: posting?.status ?? "draft", technical_stacks: posting?.technical_stacks ?? [] }); const [stack, setStack] = useState(""); const [errors, setErrors] = useState<string[]>([]); const [notice, setNotice] = useState(""); const [saving, setSaving] = useState(false); const busy = useRef(false);
  const change = (field: keyof JobPostingInput, next: string) => setValue((current) => ({ ...current, [field]: next }));
  async function submit(event: FormEvent) { event.preventDefault(); if (busy.current) return; busy.current = true; setSaving(true); setErrors([]); setNotice(""); try { const saved = await saveCompanyJobPosting(posting?.id ?? null, value); if (posting) { setNotice("募集を更新しました"); } else { router.replace(`/company/jobs?created=${saved.id}`); } } catch (reason) { setErrors(reason && typeof reason === "object" && "errors" in reason ? (reason as { errors: { message: string }[] }).errors.map((item) => item.message) : ["通信に失敗しました"]); } finally { busy.current = false; setSaving(false); } }
  function add() { const name = stack.trim(); if (name && value.technical_stacks.length < 20) { setValue((current) => ({ ...current, technical_stacks: [...current.technical_stacks, name] })); setStack(""); } }
  return <form className={styles.form} onSubmit={submit} noValidate>{notice ? <p className={styles.success} role="status">{notice}</p> : null}{errors.map((error) => <p className={styles.error} key={error}>{error}</p>)}<section className={styles.formSection}><h2>企業情報</h2><p>この内容は自社のすべての募集に共通で表示されます。</p><Field label="企業紹介" value={value.company_description} max={2000} area onChange={(v) => change("company_description", v)} /><Field label="企業ホームページ" value={value.company_website_url} max={2048} type="url" onChange={(v) => change("company_website_url", v)} /></section><section className={styles.formSection}><h2>募集内容</h2><Field label="タイトル" value={value.title} max={100} onChange={(v) => change("title", v)} /><Field label="業務内容" value={value.description} max={2000} area onChange={(v) => change("description", v)} /><Field label="勤務条件" value={value.work_conditions} max={1000} area onChange={(v) => change("work_conditions", v)} /><label className={styles.field}>技術スタックを追加<input value={stack} maxLength={50} onChange={(e) => setStack(e.target.value)} /></label><button className={styles.button} type="button" onClick={add}>追加</button><ul className={styles.stacks}>{value.technical_stacks.map((item) => <li key={item}>{item}</li>)}</ul><label><input aria-label="公開する" type="checkbox" checked={value.status === "published"} onChange={(e) => change("status", e.target.checked ? "published" : "draft")} />公開する</label></section><button className={styles.button} type="submit" disabled={saving}>{saving ? "保存中…" : "募集を保存"}</button></form>;
}
function Field({ label, value, max, area, type, onChange }: { label: string; value: string; max: number; area?: boolean; type?: string; onChange: (value: string) => void }) { return <label className={styles.field}>{label}{area ? <textarea value={value} maxLength={max} onChange={(e) => onChange(e.target.value)} /> : <input type={type} value={value} maxLength={max} onChange={(e) => onChange(e.target.value)} />}</label>; }
