"use client";
import { FormEvent, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { saveCompanyJobPosting } from "./job-posting-api";
import type { JobPosting, JobPostingInput } from "./job-posting-types";
import styles from "./job-postings.module.css";

export function JobPostingForm({ posting }: { posting: JobPosting | null }) {
  const router = useRouter(); const [value, setValue] = useState<JobPostingInput>({ title: posting?.title ?? "", description: posting?.description ?? "", work_conditions: posting?.work_conditions ?? "", status: posting?.status ?? "draft", technical_stacks: posting?.technical_stacks ?? [] }); const [stack, setStack] = useState(""); const [errors, setErrors] = useState<string[]>([]); const [saving, setSaving] = useState(false); const busy = useRef(false);
  const change = (field: keyof JobPostingInput, next: string) => setValue((current) => ({ ...current, [field]: next }));
  async function submit(event: FormEvent) { event.preventDefault(); if (busy.current) return; busy.current = true; setSaving(true); try { const saved = await saveCompanyJobPosting(posting?.id ?? null, value); router.push(`/company/jobs/${saved.id}/edit`); } catch (reason) { setErrors(reason && typeof reason === "object" && "errors" in reason ? (reason as { errors: { message: string }[] }).errors.map((item) => item.message) : ["通信に失敗しました"]); } finally { busy.current = false; setSaving(false); } }
  function add() { const name = stack.trim(); if (name && value.technical_stacks.length < 20) { setValue((current) => ({ ...current, technical_stacks: [...current.technical_stacks, name] })); setStack(""); } }
  return <form className={styles.form} onSubmit={submit} noValidate>{errors.map((error) => <p className={styles.error} key={error}>{error}</p>)}<Field label="タイトル" value={value.title} max={100} onChange={(v) => change("title", v)} /><Field label="業務内容" value={value.description} max={2000} area onChange={(v) => change("description", v)} /><Field label="勤務条件" value={value.work_conditions} max={1000} area onChange={(v) => change("work_conditions", v)} /><label className={styles.field}>技術スタックを追加<input value={stack} maxLength={50} onChange={(e) => setStack(e.target.value)} /></label><button className={styles.button} type="button" onClick={add}>追加</button><ul className={styles.stacks}>{value.technical_stacks.map((item) => <li key={item}>{item}</li>)}</ul><label><input aria-label="公開する" type="checkbox" checked={value.status === "published"} onChange={(e) => change("status", e.target.checked ? "published" : "draft")} />公開する</label><button className={styles.button} disabled={saving}>募集を保存</button></form>;
}
function Field({ label, value, max, area, onChange }: { label: string; value: string; max: number; area?: boolean; onChange: (value: string) => void }) { return <label className={styles.field}>{label}{area ? <textarea value={value} maxLength={max} onChange={(e) => onChange(e.target.value)} /> : <input value={value} maxLength={max} onChange={(e) => onChange(e.target.value)} />}</label>; }
